{% set name = "fps-frontend" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_frontend-{{ version }}.tar.gz
  sha256: ceaab9cd856a3676a6e0e3e2e7c4851ac259c0146c79c673b1adbda53b521261

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.1.4,<1

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_frontend

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  summary: An FPS plugin for the frontend related configuration
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
