{% set name = "fps-frontend" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_frontend-{{ version }}.tar.gz
  sha256: 54cc2953058529028c899e7a6603ef5acc7ba45c4ac2f7e1e96483d747d7723f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1

test:
  imports:
    - fps_frontend

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  summary: An FPS plugin for the frontend related configuration
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
