{% set name = "fps-frontend" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_frontend-{{ version }}.tar.gz
  sha256: 4ce7975c81e650d2e62e7d8b19a684092bc593f721ac01bfd3adb4bffd7c98be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.9.0,<0.10.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_frontend

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  summary: An FPS plugin for the frontend related configuration
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
