schema_version: 1

context:
  version: "0.10.1"

package:
  name: fps-frontend
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-frontend/fps_frontend-${{ version }}.tar.gz
    sha256: 0ec271cb3c6659f70134c13aa58c61319f07af06207e809eda92d464caf173f8

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - fps
    - jupyverse-frontend >=0.1.0,<0.2.0

tests:
  - python:
      imports: fps_frontend
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/frontend
  summary: An FPS plugin for the frontend related configuration

extra:
  recipe-maintainers:
    - davidbrochart
